version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: tasker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: tasker-api
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: tasker
      PORT: 3000
      CORS_ORIGIN: "*"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

  frontend:
    build: ./frontend
    container_name: tasker-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
